window.PARENTS_FAQ={
en:{
intro:"This free, ad-free site builds genuine AI literacy in children aged 3–17 — not just how to use AI tools, but how to think critically about them. Every fact links to a verified source. Progress stays on the device; nothing is collected or transmitted.",
priv_h:"🔒 Zero data collection",
priv:"No cookies, no tracking, no accounts. Progress lives in your browser's localStorage and never leaves the device. The certificate number is a SHA-256 hash generated locally from a timestamp — no server involved. Source code is public under GPL v3.",
src_h:"📚 Verified sources",
src:"Facts link to primary sources: arXiv preprints, UNESCO reports, MIT Media Lab research, EU AI Act, Stanford Internet Observatory. No sensationalism, no anthropomorphizing AI.",
discuss_h:"💬 Conversation starters for your family",
discuss:["Can Alexa miss you when you're away? How do you know?","If AI wrote a story — who is the real author?","What can AI do better than people? What can people do better?","If AI says something is true — how would you verify it?","Would you trust AI to make an important decision for you? Why or why not?"],
faq_h:"Frequently Asked Questions",
faq:[
{q:"From what age should I start explaining AI to my child?",a:"Children aged 3–4 already interact with AI through voice assistants. MIT Media Lab research (Resnick, 2017) shows children aged 5–6 can grasp basic algorithmic concepts through play. Don't wait for a 'right age' — start with simple observations: 'Siri doesn't understand jokes because she doesn't feel anything.' The key principle: concepts should precede tools by 1–2 years. A child using AI before understanding what it is builds passive dependence, not active literacy. Early conversations — AI is a tool, not a friend or a brain — protect against uncritical trust later."},
{q:"How do I explain AI to a child aged 4–7?",a:"Use the cookbook analogy: 'AI is like an enormous recipe book — it knows a million recipes but doesn't know when you're hungry.' Or: 'Imagine you've seen 10,000 cat pictures. Now you can spot a cat instantly. AI does the same with data.' Avoid the word 'smart' — it creates false anthropomorphism. Say 'well-trained' or 'very good at patterns' instead. Make it physical: sort objects by colour and shape together, then explain this is exactly what AI does with numbers. Hands-on analogies at this age outlast any verbal definition."},
{q:"What should children never share with AI chatbots?",a:"Treat AI like a public notice board — assume anything typed could theoretically be read by a stranger. Specifically: full name combined with home address, passwords, payment information, medical details, intimate photos. For young children one rule works best: 'If you wouldn't shout it in a shopping centre, don't type it to AI.' Teach this as a habit, not a scare tactic — children who understand the why are far more consistent than those simply told no. The EU AI Act (2024) classifies AI systems interacting with children as high-risk, requiring extra transparency safeguards."},
{q:"What are AI hallucinations — and how do I explain them?",a:"AI hallucinations are confident wrong answers. A language model may cite a non-existent book, invent a fake author, or state a fabricated statistic with complete certainty. For children: 'Imagine a classmate who never admits they don't know — they always make something up. That's how AI works when it's uncertain.' This is not a bug being fixed — it is an architectural feature of how language models predict text. Practical rule for children 8+: any AI-provided fact needs verification in at least one independent source. This single habit is the most important digital-literacy skill of the current decade."},
{q:"Can AI replace a teacher?",a:"No — and understanding why matters. UNESCO's AI in Education report (2023) notes that AI lacks pedagogical intuition: it cannot detect that a child is confused, emotionally unavailable, or needs a fundamentally different explanation. AI cannot model intellectual humility, social negotiation, or the joy of shared discovery. Best framing: AI is a knowledgeable study partner, not a teacher. The real risk is substitution: children who use AI to generate answers rather than think through problems progressively lose independent reasoning. A healthy pattern — think for 5 minutes, then ask AI, then verify with a human — preserves both benefits."},
{q:"How do I prevent AI dependency in my child?",a:"Three evidence-informed rules: (1) Think-first — AI is consulted only after a genuine 5-minute solo attempt. (2) Teach-back — after using AI, the child must explain the answer in their own words; if they can't, they copied rather than learned. (3) One AI-free day per week, framed positively: 'training your own brain the way athletes train their body, not just their equipment.' Research on skill acquisition (Ericsson, 1993) confirms that effortful retrieval — struggling to remember or solve — is what builds lasting neural pathways. Instant AI answers bypass this process entirely."},
{q:"What jobs will exist for my child in the AI era?",a:"World Economic Forum Future of Jobs Report (2024): 70% of jobs will change significantly within 5 years. New roles include AI Ethics Reviewer, Human-AI Interaction Designer, and AI Trainer. Persistently in-demand roles require physical dexterity plus judgment (surgeons, builders, craftspeople) or genuine empathy (therapists, teachers, carers). More important than specific job titles: the meta-skill of working alongside AI — knowing when to trust it, when to challenge it, how to verify its outputs. Children who understand AI's limits and capabilities will have a decisive advantage over both those who avoid AI and those who defer to it uncritically."}
],
proto_by:"By the same author:",proto_desc:"A systematic guide to mindset rebooting in the AI era — 33 evidence-based protocols for conscious adaptation.",
cta_self:"Take the test yourself →",cta_child:"← Set up for child"
},

ru:{
intro:"Этот бесплатный сайт без рекламы формирует настоящую ИИ-грамотность у детей 3–17 лет — не просто умение пользоваться инструментами, а навык критически о них думать. Каждый факт привязан к верифицированным источникам. Прогресс остаётся на устройстве; ничего не собирается и не передаётся.",
priv_h:"🔒 Ноль сбора данных",
priv:"Никаких куки, трекинга, аккаунтов. Прогресс хранится в localStorage браузера и никогда не покидает устройство. Номер сертификата — SHA-256 хэш, генерируется локально по временной метке; сервер не задействован. Исходный код открыт по лицензии GPL v3.",
src_h:"📚 Верифицированные источники",
src:"Факты привязаны к первоисточникам: препринты arXiv, доклады ЮНЕСКО, MIT Media Lab, Закон ЕС об ИИ, Яндекс Учебник, Стэнфордская интернет-обсерватория. Никакой сенсационности, никакой антропоморфизации ИИ.",
discuss_h:"💬 Темы для разговора с ребёнком",
discuss:["Может ли Алиса скучать по тебе? Откуда ты знаешь?","Если ИИ написал рассказ — кто настоящий автор?","Что умеет ИИ лучше людей? А что люди делают лучше ИИ?","Если ИИ говорит что это правда — как ты проверишь?","Доверил бы ты ИИ принять за тебя важное решение? Почему?"],
faq_h:"Часто задаваемые вопросы",
faq:[
{q:"С какого возраста объяснять ребёнку, что такое ИИ?",a:"Дети 3–4 лет уже взаимодействуют с ИИ через голосовых помощников. Исследования MIT Media Lab (Resnick, 2017) показывают: дети 5–6 лет осваивают базовые алгоритмические концепции через игру. Не ждите «правильного возраста» — начинайте с простых наблюдений: «Алиса не понимает шуток, потому что не чувствует». Ключевой принцип: концепции должны опережать инструменты на 1–2 года. Ребёнок, использующий ИИ без понимания что это такое, приобретает пассивную зависимость, а не активную грамотность. Ранние разговоры о том, что ИИ — инструмент, а не друг и не мозг — защищают от некритичного доверия в будущем."},
{q:"Как объяснить ИИ ребёнку 4–7 лет?",a:"Используйте аналогию с поваренной книгой: «ИИ — это очень толстая книга рецептов. Знает миллион рецептов, но не знает, когда ты голоден». Или: «Представь, посмотрел 10 000 картинок кошек. Теперь узнаёшь кошку с первого взгляда. ИИ делает то же самое с данными». Избегайте слова «умный» — оно создаёт ложную антропоморфизацию. Говорите «хорошо обученный» или «умелый в поиске паттернов». Сортируйте предметы по цвету и форме вместе, потом объясните — именно это ИИ делает с числами. Практические аналогии у детей этого возраста работают намного лучше словесных определений."},
{q:"Что нельзя сообщать ИИ-чатботам?",a:"Относитесь к ИИ как к публичному стенду: считайте, что всё напечатанное теоретически может прочитать посторонний. Конкретно под запретом: полное имя + домашний адрес вместе, пароли, платёжные данные, медицинские сведения, интимные фотографии. Для маленьких детей: «Если бы ты не крикнул это в торговом центре — не пиши в ИИ». Преподносите как привычку, не запугивание: дети, понимающие «почему», намного последовательнее тех, кому просто говорят «нельзя». Закон ЕС об ИИ (2024) относит системы, взаимодействующие с детьми, к группе высокого риска."},
{q:"Что такое галлюцинации ИИ и как это объяснить ребёнку?",a:"Галлюцинации ИИ — уверенные неправильные ответы. Языковая модель может процитировать несуществующую книгу, выдумать автора или привести сфабрикованную статистику с абсолютной уверенностью. Для ребёнка: «Представь одноклассника, который никогда не признаётся что не знает — всегда что-то придумает. Вот так работает ИИ когда не уверен». Это не баг который исправят — это архитектурная особенность языковых моделей. Правило для детей 8+: любой факт из ИИ нужно проверить хотя бы в одном независимом источнике. Этот навык — важнейший элемент цифровой грамотности текущего десятилетия."},
{q:"Может ли ИИ заменить учителя?",a:"Нет — и понять почему важно. Доклад ЮНЕСКО «AI in Education» (2023): у ИИ нет педагогической интуиции — он не видит, что ребёнок запутался, устал или нуждается в принципиально другом объяснении. ИИ не способен моделировать интеллектуальную скромность, социальное взаимодействие или радость совместного открытия. Лучшая формулировка: ИИ — знающий партнёр по учёбе, но не учитель. Реальный риск — замещение: дети, использующие ИИ для генерации ответов вместо осмысления, постепенно теряют способность к независимому рассуждению. Здоровый паттерн: 5 минут подумать самому → спросить ИИ → проверить с человеком."},
{q:"Как не допустить зависимости ребёнка от ИИ?",a:"Три правила, подтверждённых исследованиями: (1) Сначала подумай: ИИ открывается только после честной 5-минутной попытки решить самому. (2) Объясни мне: после ИИ ребёнок объясняет ответ своими словами — не может, значит скопировал, а не понял. (3) Один день в неделю без ИИ — формулируйте позитивно: «тренируем собственный мозг, как спортсмен тренирует тело, а не только инвентарь». Исследования усвоения навыков (Ericsson, 1993): именно усилие вспомнить и решить самостоятельно строит устойчивые нейронные связи. Мгновенные ответы ИИ полностью обходят этот процесс."},
{q:"Какие профессии ждут моего ребёнка в эпоху ИИ?",a:"World Economic Forum Future of Jobs Report (2024): 70% рабочих мест претерпят значительные изменения в ближайшие 5 лет. Новые роли: Ревьюер этики ИИ, Дизайнер взаимодействия человек–ИИ, Тренер ИИ. Устойчиво востребованные: роли с физической ловкостью и суждением (хирурги, строители, мастера) или настоящей эмпатией (психологи, учителя, воспитатели). Важнее конкретных профессий — метанавык работать рядом с ИИ: знать когда доверять, когда сомневаться, как проверять. Дети, понимающие ограничения и возможности ИИ, получат решающее преимущество перед теми, кто его избегает, и перед теми, кто ему некритично доверяет."}
],
proto_by:"От того же автора:",proto_desc:"Системное руководство по перезагрузке мышления в эпоху ИИ — 33 протокола осознанной адаптации на доказательной базе.",
cta_self:"Пройти тест самому →",cta_child:"← Настроить для ребёнка"
},

de:{
intro:"Diese kostenlose, werbefreie Website fördert echte KI-Kompetenz bei Kindern von 3–17 Jahren — nicht nur die Nutzung von KI-Tools, sondern kritisches Denken darüber. Jede Tatsache ist mit einer verifizierten Quelle verknüpft. Fortschritt bleibt auf dem Gerät; nichts wird gesammelt oder übertragen.",
priv_h:"🔒 Null Datenerhebung",
priv:"Keine Cookies, kein Tracking, keine Konten. Der Fortschritt wird im localStorage des Browsers gespeichert und verlässt das Gerät nie. Die Zertifikatsnummer ist ein SHA-256-Hash, der lokal aus einem Zeitstempel generiert wird. Quellcode ist unter GPL v3 öffentlich.",
src_h:"📚 Geprüfte Quellen",
src:"Fakten verlinken auf Primärquellen: arXiv-Preprints, UNESCO-Berichte, MIT Media Lab, EU AI Act, Stanford Internet Observatory. Keine Sensationsmacherei, keine Anthropomorphisierung von KI.",
discuss_h:"💬 Gesprächsthemen für Ihre Familie",
discuss:["Kann Alexa dich vermissen, wenn du weg bist? Woher weißt du das?","Wenn KI eine Geschichte schrieb — wer ist der echte Autor?","Was kann KI besser als Menschen? Was können Menschen besser?","Wenn KI sagt, etwas ist wahr — wie würdest du es überprüfen?","Würdest du KI eine wichtige Entscheidung für dich treffen lassen? Warum?"],
faq_h:"Häufig gestellte Fragen",
faq:[
{q:"Ab welchem Alter sollte ich meinem Kind KI erklären?",a:"Kinder ab 3–4 Jahren interagieren bereits täglich über Sprachassistenten mit KI. MIT Media Lab-Forschung (Resnick, 2017) zeigt: Kinder ab 5–6 Jahren können grundlegende algorithmische Konzepte spielerisch erfassen. Warten Sie nicht auf das 'richtige Alter' — beginnen Sie mit einfachen Beobachtungen: 'Siri versteht keine Witze, weil sie nichts fühlt.' Leitprinzip: Konzepte sollten Werkzeugen um 1–2 Jahre vorausgehen. Ein Kind, das KI benutzt, bevor es versteht was sie ist, entwickelt passive Abhängigkeit statt aktiver Kompetenz."},
{q:"Wie erkläre ich KI einem 4–7-jährigen Kind?",a:"Nutzen Sie die Kochbuch-Analogie: 'KI ist wie ein riesiges Rezeptbuch — es kennt eine Million Rezepte, weiß aber nicht, wann du hungrig bist.' Oder: 'Stell dir vor, du hast 10.000 Katzenbilder gesehen. Jetzt erkennst du sofort eine Katze. KI macht dasselbe mit Daten.' Vermeiden Sie das Wort 'intelligent' — es erzeugt falsche Anthropomorphisierung. Sagen Sie stattdessen 'gut trainiert' oder 'sehr gut im Mustererkennen'. Sortieren Sie gemeinsam Gegenstände nach Farbe — dann erklären Sie, das macht KI mit Zahlen."},
{q:"Was sollten Kinder KI-Chatbots nie mitteilen?",a:"Behandeln Sie KI wie ein öffentliches Schwarzes Brett — gehen Sie davon aus, dass alles Eingetippte theoretisch von Fremden gelesen werden kann. Verboten: vollständiger Name + Heimadresse zusammen, Passwörter, Zahlungsinformationen, medizinische Details, intime Fotos. Für kleine Kinder: 'Was du nicht in einem Einkaufszentrum schreien würdest, tipps du auch nicht in KI.' Der EU AI Act (2024) stuft KI-Systeme, die mit Kindern interagieren, als Hochrisiko ein."},
{q:"Was sind KI-Halluzinationen — und wie erkläre ich sie?",a:"KI-Halluzinationen sind selbstsichere falsche Antworten. Ein Sprachmodell kann ein nicht existierendes Buch zitieren, einen erfundenen Autor nennen oder eine gefälschte Statistik mit völliger Überzeugung präsentieren. Für Kinder: 'Stell dir einen Mitschüler vor, der nie zugibt, etwas nicht zu wissen — er erfindet immer etwas. So funktioniert KI, wenn sie unsicher ist.' Praktische Regel für Kinder ab 8: Jede KI-Tatsache in mindestens einer unabhängigen Quelle überprüfen."},
{q:"Kann KI einen Lehrer ersetzen?",a:"Nein — und das Verstehen warum ist wichtig. UNESCOs KI-in-Bildung-Bericht (2023): KI fehlt pädagogische Intuition — sie sieht nicht, dass ein Kind verwirrt, erschöpft ist oder eine grundlegend andere Erklärung braucht. KI kann keine intellektuelle Bescheidenheit, soziale Aushandlung oder die Freude gemeinsamer Entdeckung modellieren. Beste Formulierung: KI ist ein wissender Lernpartner, kein Lehrer. Gesundes Muster: 5 Minuten allein denken → KI fragen → mit einem Menschen überprüfen."},
{q:"Wie verhindere ich KI-Abhängigkeit bei meinem Kind?",a:"Drei evidenzbasierte Regeln: (1) Erst denken: KI wird erst konsultiert nach einem echten 5-minütigen Alleinversuch. (2) Erklär's mir: Nach KI-Nutzung muss das Kind die Antwort in eigenen Worten erklären; wenn nicht möglich, wurde kopiert statt gelernt. (3) Ein KI-freier Tag pro Woche — positiv formuliert: 'das eigene Gehirn trainieren, wie Sportler ihren Körper trainieren, nicht nur ihre Ausrüstung.' Forschung zur Kompetenzentwicklung (Ericsson, 1993) bestätigt: anstrengendes Erinnern und Lösen baut dauerhafte neuronale Bahnen auf."},
{q:"Welche Berufe wird es für mein Kind im KI-Zeitalter geben?",a:"WEF Future of Jobs Report (2024): 70% der Arbeitsplätze werden sich in 5 Jahren erheblich verändern. Neue Rollen: KI-Ethik-Reviewer, Mensch-KI-Interaktionsdesigner, KI-Trainer. Dauerhaft gefragt: Berufe mit körperlicher Geschicklichkeit und Urteilsvermögen (Chirurgen, Handwerker) oder echter Empathie (Therapeuten, Lehrer, Erzieher). Wichtiger als spezifische Berufe: die Metakompetenz, effektiv neben KI zu arbeiten — wissen, wann man ihr vertraut, wann man sie hinterfragt, wie man ihre Ausgaben überprüft."}
],
proto_by:"Vom selben Autor:",proto_desc:"Ein systematischer Leitfaden zur Neukalibrierung des Denkens im KI-Zeitalter — 33 evidenzbasierte Protokolle zur bewussten Anpassung.",
cta_self:"Test selbst machen →",cta_child:"← Für Kind einrichten"
},

es:{
intro:"Este sitio gratuito y sin publicidad desarrolla una verdadera alfabetización en IA en niños de 3 a 17 años — no solo cómo usar herramientas de IA, sino cómo pensar críticamente sobre ellas. Cada dato está vinculado a una fuente verificada. El progreso queda en el dispositivo; nada se recopila ni transmite.",
priv_h:"🔒 Cero recopilación de datos",
priv:"Sin cookies, sin seguimiento, sin cuentas. El progreso se almacena en el localStorage del navegador y nunca sale del dispositivo. El número de certificado es un hash SHA-256 generado localmente a partir de una marca de tiempo. El código fuente es público bajo GPL v3.",
src_h:"📚 Fuentes verificadas",
src:"Los datos enlazan a fuentes primarias: preprints de arXiv, informes de la UNESCO, MIT Media Lab, Ley de IA de la UE, Observatorio de Internet de Stanford. Sin sensacionalismo, sin antropomorfizar la IA.",
discuss_h:"💬 Temas de conversación para su familia",
discuss:["¿Puede Alexa extrañarte cuando no estás? ¿Cómo lo sabes?","Si la IA escribió una historia — ¿quién es el verdadero autor?","¿Qué puede hacer la IA mejor que las personas? ¿Qué hacen mejor las personas?","Si la IA dice que algo es verdad — ¿cómo lo verificarías?","¿Confiarías en la IA para tomar una decisión importante? ¿Por qué sí o no?"],
faq_h:"Preguntas frecuentes",
faq:[
{q:"¿A partir de qué edad debo explicar la IA a mi hijo?",a:"Los niños de 3 a 4 años ya interactúan con la IA a través de asistentes de voz. La investigación del MIT Media Lab (Resnick, 2017) muestra que los niños de 5 a 6 años pueden comprender conceptos algorítmicos básicos mediante el juego. No espere la 'edad correcta' — comience con observaciones simples: 'Siri no entiende los chistes porque no siente nada.' Principio clave: los conceptos deben preceder a las herramientas en 1 a 2 años. Un niño que usa IA sin entender qué es desarrolla dependencia pasiva en lugar de alfabetización activa."},
{q:"¿Cómo explico la IA a un niño de 4 a 7 años?",a:"Use la analogía del libro de recetas: 'La IA es como un libro de recetas enorme — conoce un millón de recetas pero no sabe cuándo tienes hambre.' O: 'Imagina que viste 10.000 fotos de gatos. Ahora reconoces un gato al instante. La IA hace lo mismo con los datos.' Evite la palabra 'inteligente' — crea falsa antropomorfización. Diga 'bien entrenada' o 'muy buena con patrones'. Clasifiquen objetos por color juntos y luego explique que eso es exactamente lo que la IA hace con los números."},
{q:"¿Qué nunca deben compartir los niños con los chatbots de IA?",a:"Trate la IA como un tablón de anuncios público: suponga que todo lo escrito podría leerlo un extraño. En concreto: nombre completo más dirección de casa juntos, contraseñas, datos de pago, diagnósticos médicos, fotos íntimas. Para niños pequeños: 'Si no lo gritarías en un centro comercial, no lo escribas en la IA.' Enséñelo como hábito, no como amenaza. La Ley de IA de la UE (2024) clasifica los sistemas de IA que interactúan con niños como de alto riesgo."},
{q:"¿Qué son las alucinaciones de IA y cómo las explico?",a:"Las alucinaciones de IA son respuestas incorrectas pero confiadas. Un modelo de lenguaje puede citar un libro inexistente o inventar estadísticas falsas con total certeza. Para los niños: 'Imagina un compañero de clase que nunca admite no saber algo — siempre inventa algo. Así funciona la IA cuando no está segura.' Regla práctica para niños mayores de 8 años: cualquier dato de la IA debe verificarse en al menos una fuente independiente."},
{q:"¿Puede la IA reemplazar a un maestro?",a:"No — y entender por qué importa. El informe de la UNESCO sobre IA en Educación (2023): la IA carece de intuición pedagógica — no puede detectar que un niño está confundido, cansado o necesita una explicación fundamentalmente diferente. La IA no puede modelar humildad intelectual ni la alegría del descubrimiento compartido. Mejor marco: la IA es un compañero de estudio con mucho conocimiento, no un maestro. Patrón saludable: pensar 5 minutos solo → preguntar a la IA → verificar con un humano."},
{q:"¿Cómo prevengo la dependencia de la IA en mi hijo?",a:"Tres reglas basadas en evidencia: (1) Primero pensar — la IA solo se consulta tras un intento genuino de 5 minutos en solitario. (2) Explicar — tras usar la IA, el niño debe explicar la respuesta con sus propias palabras; si no puede, copió en lugar de aprender. (3) Un día sin IA por semana, formulado positivamente: 'entrenar el propio cerebro como los deportistas entrenan su cuerpo.' La investigación sobre adquisición de habilidades (Ericsson, 1993) confirma que el esfuerzo de recuperación construye vías neurales duraderas."},
{q:"¿Qué empleos habrá para mi hijo en la era de la IA?",a:"WEF Future of Jobs Report (2024): el 70% de los empleos cambiarán significativamente en 5 años. Nuevos roles: Revisor de Ética de IA, Diseñador de Interacción Humano-IA, Entrenador de IA. Empleos persistentemente demandados: los que requieren destreza física y criterio (cirujanos, artesanos) o empatía genuina (terapeutas, maestros, cuidadores). Más importante que los títulos específicos: la metacompetencia de trabajar junto a la IA — saber cuándo confiar, cuándo cuestionar, cómo verificar."}
],
proto_by:"Del mismo autor:",proto_desc:"Una guía sistemática para reiniciar la mentalidad en la era de la IA — 33 protocolos basados en evidencia para la adaptación consciente.",
cta_self:"Hacer el test yo mismo →",cta_child:"← Configurar para el niño"
},

fr:{
intro:"Ce site gratuit et sans publicité développe une véritable culture de l'IA chez les enfants de 3 à 17 ans — pas seulement l'utilisation des outils IA, mais la pensée critique à leur égard. Chaque fait est lié à une source vérifiée. Les progrès restent sur l'appareil ; rien n'est collecté ni transmis.",
priv_h:"🔒 Zéro collecte de données",
priv:"Pas de cookies, pas de suivi, pas de comptes. Les progrès sont stockés dans le localStorage du navigateur et ne quittent jamais l'appareil. Le numéro de certificat est un hash SHA-256 généré localement à partir d'un horodatage. Le code source est public sous GPL v3.",
src_h:"📚 Sources vérifiées",
src:"Les faits renvoient aux sources primaires : prépublications arXiv, rapports UNESCO, MIT Media Lab, Loi européenne sur l'IA, Observatoire Internet de Stanford. Pas de sensationnalisme, pas d'anthropomorphisation de l'IA.",
discuss_h:"💬 Sujets de conversation pour votre famille",
discuss:["L'IA peut-elle vous manquer quand vous êtes absent ? Comment le sauriez-vous ?","Si l'IA a écrit une histoire — qui est le vrai auteur ?","Que peut faire l'IA mieux que les humains ? Et les humains ?","Si l'IA dit que quelque chose est vrai — comment le vérifieriez-vous ?","Feriez-vous confiance à l'IA pour prendre une décision importante ? Pourquoi ?"],
faq_h:"Questions fréquentes",
faq:[
{q:"À partir de quel âge expliquer l'IA à mon enfant ?",a:"Les enfants de 3 à 4 ans interagissent déjà avec l'IA via les assistants vocaux. La recherche du MIT Media Lab (Resnick, 2017) montre que les enfants de 5 à 6 ans peuvent comprendre des concepts algorithmiques de base par le jeu. N'attendez pas le 'bon âge' — commencez par des observations simples : 'Siri ne comprend pas les blagues parce qu'elle ne ressent rien.' Principe clé : les concepts doivent précéder les outils de 1 à 2 ans. Un enfant qui utilise l'IA sans comprendre ce que c'est développe une dépendance passive plutôt qu'une véritable culture."},
{q:"Comment expliquer l'IA à un enfant de 4 à 7 ans ?",a:"Utilisez l'analogie du livre de recettes : 'L'IA est comme un énorme livre de recettes — elle connaît un million de recettes mais ne sait pas quand tu as faim.' Ou : 'Imagine que tu as vu 10 000 photos de chats. Maintenant tu reconnais un chat instantanément. L'IA fait la même chose avec les données.' Évitez le mot 'intelligent' — cela crée une anthropomorphisation. Dites plutôt 'bien entraîné' ou 'très doué pour les modèles'. Triez ensemble des objets par couleur, puis expliquez que c'est exactement ce que fait l'IA avec des chiffres."},
{q:"Que ne doivent jamais partager les enfants avec les chatbots IA ?",a:"Traitez l'IA comme un tableau d'affichage public : supposez que tout ce qui est tapé pourrait être lu par un inconnu. Précisément : nom complet + adresse combinés, mots de passe, données de paiement, diagnostics médicaux, photos intimes. Pour les jeunes enfants : 'Ce que tu ne crierais pas dans un centre commercial, ne le tape pas à l'IA.' La Loi européenne sur l'IA (2024) classe les systèmes IA interagissant avec des enfants comme à haut risque, nécessitant des garanties de transparence supplémentaires."},
{q:"Que sont les hallucinations de l'IA — et comment les expliquer ?",a:"Les hallucinations de l'IA sont des réponses fausses mais confiantes. Un modèle de langage peut citer un livre inexistant ou inventer des statistiques fabriquées avec une totale certitude. Pour les enfants : 'Imagine un camarade qui n'admet jamais ne pas savoir — il invente toujours quelque chose. C'est ainsi que l'IA fonctionne quand elle est incertaine.' Règle pratique pour les enfants de 8 ans et plus : tout fait fourni par l'IA doit être vérifié dans au moins une source indépendante."},
{q:"L'IA peut-elle remplacer un enseignant ?",a:"Non — et comprendre pourquoi importe. Le rapport UNESCO sur l'IA dans l'éducation (2023) : l'IA manque d'intuition pédagogique — elle ne peut pas détecter qu'un enfant est confus, fatigué ou a besoin d'une explication fondamentalement différente. L'IA ne peut pas modéliser l'humilité intellectuelle ni la joie de la découverte partagée. Meilleure formulation : l'IA est un partenaire d'étude compétent, pas un enseignant. Schéma sain : réfléchir 5 minutes seul → demander à l'IA → vérifier avec un humain."},
{q:"Comment prévenir la dépendance à l'IA chez mon enfant ?",a:"Trois règles fondées sur des preuves : (1) Penser d'abord — l'IA n'est consultée qu'après une tentative solo sincère de 5 minutes. (2) Expliquer — après avoir utilisé l'IA, l'enfant doit expliquer la réponse avec ses propres mots ; s'il ne peut pas, il a copié plutôt qu'appris. (3) Un jour sans IA par semaine, formulé positivement : 'entraîner son propre cerveau comme les athlètes entraînent leur corps.' La recherche sur l'acquisition de compétences (Ericsson, 1993) confirme que l'effort de récupération construit des voies neuronales durables."},
{q:"Quels emplois y aura-t-il pour mon enfant à l'ère de l'IA ?",a:"Rapport WEF Future of Jobs (2024) : 70% des emplois changeront significativement dans 5 ans. Nouveaux rôles : Auditeur d'éthique IA, Designer Interaction Humain-IA, Entraîneur IA. Emplois durablement demandés : ceux nécessitant dextérité physique et jugement (chirurgiens, artisans) ou une empathie réelle (thérapeutes, enseignants, soignants). Plus important que les titres de poste : la méta-compétence de travailler efficacement aux côtés de l'IA — savoir quand lui faire confiance, quand la remettre en question."}
],
proto_by:"Du même auteur :",proto_desc:"Un guide systématique pour reprogrammer sa mentalité à l'ère de l'IA — 33 protocoles basés sur des preuves pour une adaptation consciente.",
cta_self:"Faire le test moi-même →",cta_child:"← Configurer pour l'enfant"
},

hi:{
intro:"यह मुफ़्त, विज्ञापन-मुक्त साइट 3–17 वर्ष के बच्चों में वास्तविक AI साक्षरता विकसित करती है — न केवल AI टूल्स का उपयोग, बल्कि उनके बारे में आलोचनात्मक सोच। हर तथ्य एक सत्यापित स्रोत से जुड़ा है। प्रगति डिवाइस पर ही रहती है; कुछ भी एकत्र या प्रसारित नहीं होता।",
priv_h:"🔒 शून्य डेटा संग्रह",
priv:"कोई कुकीज़ नहीं, कोई ट्रैकिंग नहीं, कोई अकाउंट नहीं। प्रगति ब्राउज़र के localStorage में संग्रहीत होती है और डिवाइस कभी नहीं छोड़ती। सर्टिफिकेट नंबर स्थानीय रूप से SHA-256 हैश है। सोर्स कोड GPL v3 के तहत सार्वजनिक है।",
src_h:"📚 सत्यापित स्रोत",
src:"तथ्य प्राथमिक स्रोतों से जुड़े हैं: arXiv प्रीप्रिंट, UNESCO रिपोर्ट, MIT Media Lab, EU AI Act, Stanford Internet Observatory।",
discuss_h:"💬 परिवार के साथ बातचीत के विषय",
discuss:["क्या Alexa आपके न रहने पर आपको याद कर सकती है? आप कैसे जानते हैं?","अगर AI ने कहानी लिखी — असली लेखक कौन है?","AI लोगों से बेहतर क्या कर सकता है? लोग AI से बेहतर क्या करते हैं?","अगर AI कहे कि कुछ सच है — आप इसे कैसे सत्यापित करेंगे?","क्या आप AI पर कोई महत्वपूर्ण निर्णय लेने का भरोसा करेंगे? क्यों?"],
faq_h:"अक्सर पूछे जाने वाले प्रश्न",
faq:[
{q:"किस उम्र से बच्चे को AI समझाना शुरू करें?",a:"3–4 साल के बच्चे पहले से ही वॉइस असिस्टेंट के माध्यम से AI से इंटरैक्ट करते हैं। MIT Media Lab शोध (Resnick, 2017) दिखाता है: 5–6 साल के बच्चे खेल के माध्यम से बुनियादी एल्गोरिदमिक अवधारणाओं को समझ सकते हैं। 'सही उम्र' का इंतजार न करें — सरल टिप्पणियों से शुरू करें: 'Siri मजाक नहीं समझती क्योंकि वह कुछ महसूस नहीं करती।' मुख्य सिद्धांत: अवधारणाएं टूल्स से 1–2 साल आगे होनी चाहिए।"},
{q:"4–7 साल के बच्चे को AI कैसे समझाएं?",a:"रेसिपी बुक का सादृश्य उपयोग करें: 'AI एक बड़ी रेसिपी बुक की तरह है — लाखों रेसिपी जानती है लेकिन नहीं जानती कि तुम कब भूखे हो।' या: 'सोचो तुमने 10,000 बिल्लियों की तस्वीरें देखीं। अब तुम तुरंत बिल्ली पहचान लेते हो। AI डेटा के साथ वही करती है।' 'स्मार्ट' शब्द से बचें — यह गलत मानवीकरण पैदा करता है।"},
{q:"बच्चों को AI चैटबॉट के साथ क्या साझा नहीं करना चाहिए?",a:"AI को एक सार्वजनिक सूचना बोर्ड मानें: मान लें कि टाइप की गई हर चीज़ अजनबी पढ़ सकता है। विशेष रूप से: पूरा नाम + घर का पता एक साथ, पासवर्ड, भुगतान जानकारी, चिकित्सा विवरण, अंतरंग तस्वीरें। छोटे बच्चों के लिए: 'जो तुम बाज़ार में चिल्लाकर नहीं कहोगे, वो AI में टाइप मत करो।'"},
{q:"AI हेलुसिनेशन क्या हैं — इन्हें कैसे समझाएं?",a:"AI हेलुसिनेशन आत्मविश्वास के साथ दिए गए गलत जवाब हैं। एक भाषा मॉडल अस्तित्वहीन किताब का हवाला दे सकता है या मनगढ़ंत आँकड़े पूरे यकीन के साथ बता सकता है। बच्चों के लिए: 'सोचो एक सहपाठी जो कभी नहीं मानता कि उसे नहीं पता — वह हमेशा कुछ बना लेता है। AI भी ऐसे ही काम करती है जब अनिश्चित होती है।' 8+ बच्चों के लिए नियम: किसी भी AI तथ्य को कम से कम एक स्वतंत्र स्रोत में सत्यापित करें।"},
{q:"क्या AI एक शिक्षक की जगह ले सकता है?",a:"नहीं — और यह समझना महत्वपूर्ण है। UNESCO AI in Education रिपोर्ट (2023): AI में शैक्षणिक सहज ज्ञान नहीं है — यह नहीं देख सकता कि बच्चा भ्रमित, थका हुआ है या उसे पूरी तरह अलग व्याख्या चाहिए। सबसे अच्छी परिभाषा: AI एक जानकार अध्ययन साथी है, शिक्षक नहीं। स्वस्थ पैटर्न: 5 मिनट खुद सोचो → AI से पूछो → किसी इंसान से सत्यापित करो।"},
{q:"बच्चे की AI निर्भरता कैसे रोकें?",a:"तीन साक्ष्य-आधारित नियम: (1) पहले सोचो: AI केवल 5 मिनट की वास्तविक अकेली कोशिश के बाद ही खोला जाए। (2) मुझे समझाओ: AI के बाद बच्चा उत्तर अपने शब्दों में समझाए; न कर पाए तो कॉपी किया, सीखा नहीं। (3) सप्ताह में एक AI-मुक्त दिन — सकारात्मक रूप से: 'खुद के दिमाग को प्रशिक्षित करना, जैसे खिलाड़ी अपने शरीर को।' शोध (Ericsson, 1993) पुष्टि करता है कि याद करने का प्रयास स्थायी तंत्रिका मार्ग बनाता है।"},
{q:"AI युग में मेरे बच्चे के लिए कौन से काम होंगे?",a:"WEF Future of Jobs Report (2024): 70% नौकरियाँ 5 वर्षों में बदलेंगी। नई भूमिकाएं: AI Ethics Reviewer, Human-AI Interaction Designer, AI Trainer। स्थायी मांग: शारीरिक कुशलता + निर्णय (सर्जन, कारीगर) या वास्तविक सहानुभूति (चिकित्सक, शिक्षक) वाले काम। विशिष्ट नौकरियों से अधिक महत्वपूर्ण: AI के साथ काम करने की मेटा-स्किल — कब भरोसा करें, कब सवाल करें, कैसे सत्यापित करें।"}
],
proto_by:"उसी लेखक द्वारा:",proto_desc:"AI युग में मानसिकता को रीबूट करने की व्यवस्थित मार्गदर्शिका — 33 साक्ष्य-आधारित प्रोटोकॉल।",
cta_self:"स्वयं टेस्ट दें →",cta_child:"← बच्चे के लिए सेट करें"
},

id:{
intro:"Situs gratis tanpa iklan ini membangun literasi AI sejati pada anak-anak usia 3–17 tahun — bukan hanya cara menggunakan alat AI, tetapi cara berpikir kritis tentangnya. Setiap fakta tertaut ke sumber terverifikasi. Kemajuan tersimpan di perangkat; tidak ada yang dikumpulkan atau dikirimkan.",
priv_h:"🔒 Nol pengumpulan data",
priv:"Tanpa cookie, tanpa pelacakan, tanpa akun. Kemajuan tersimpan di localStorage browser dan tidak pernah meninggalkan perangkat. Nomor sertifikat adalah hash SHA-256 yang dibuat secara lokal dari timestamp. Kode sumber publik di bawah GPL v3.",
src_h:"📚 Sumber terverifikasi",
src:"Fakta tertaut ke sumber primer: pracetak arXiv, laporan UNESCO, MIT Media Lab, UU AI UE, Stanford Internet Observatory. Tanpa sensasionalisme, tanpa antropomorfisasi AI.",
discuss_h:"💬 Topik percakapan untuk keluarga",
discuss:["Bisakah Alexa merindukanmu saat kamu pergi? Bagaimana kamu tahu?","Jika AI menulis cerita — siapa penulis sejatinya?","Apa yang bisa dilakukan AI lebih baik dari manusia? Apa yang manusia lakukan lebih baik?","Jika AI mengatakan sesuatu itu benar — bagaimana kamu memverifikasinya?","Apakah kamu akan mempercayai AI untuk membuat keputusan penting? Mengapa?"],
faq_h:"Pertanyaan yang sering diajukan",
faq:[
{q:"Mulai usia berapa saya harus menjelaskan AI kepada anak saya?",a:"Anak usia 3–4 tahun sudah berinteraksi dengan AI melalui asisten suara. Penelitian MIT Media Lab (Resnick, 2017) menunjukkan anak usia 5–6 tahun dapat memahami konsep algoritmik dasar melalui bermain. Jangan menunggu 'usia yang tepat' — mulai dengan pengamatan sederhana: 'Siri tidak mengerti lelucon karena dia tidak merasakan apa-apa.' Prinsip utama: konsep harus mendahului alat 1–2 tahun. Anak yang menggunakan AI sebelum memahaminya mengembangkan ketergantungan pasif bukan literasi aktif."},
{q:"Bagaimana saya menjelaskan AI kepada anak usia 4–7 tahun?",a:"Gunakan analogi buku resep: 'AI seperti buku resep raksasa — tahu jutaan resep tapi tidak tahu kapan kamu lapar.' Atau: 'Bayangkan kamu melihat 10.000 foto kucing. Sekarang kamu langsung mengenali kucing. AI melakukan hal yang sama dengan data.' Hindari kata 'pintar' — itu menciptakan antropomorfisasi palsu. Katakan 'terlatih dengan baik' atau 'sangat pandai mengenali pola'. Pilah benda bersama berdasarkan warna, lalu jelaskan itulah yang AI lakukan dengan angka."},
{q:"Apa yang tidak boleh anak-anak bagikan ke chatbot AI?",a:"Perlakukan AI seperti papan pengumuman publik — anggap semua yang diketik bisa dibaca orang asing. Secara spesifik: nama lengkap + alamat rumah bersama, kata sandi, informasi pembayaran, rincian medis, foto intim. Untuk anak kecil: 'Apa yang tidak akan kamu teriak di pusat perbelanjaan, jangan ketik ke AI.' UU AI UE (2024) mengklasifikasikan sistem AI yang berinteraksi dengan anak sebagai berisiko tinggi."},
{q:"Apa itu halusinasi AI — dan bagaimana menjelaskannya?",a:"Halusinasi AI adalah jawaban salah yang percaya diri. Model bahasa dapat mengutip buku yang tidak ada atau menyajikan statistik palsu dengan keyakinan penuh. Untuk anak-anak: 'Bayangkan teman sekelas yang tidak pernah mengakui tidak tahu — dia selalu mengarang sesuatu. Begitulah AI bekerja saat tidak yakin.' Aturan praktis untuk anak 8+: setiap fakta dari AI perlu diverifikasi di setidaknya satu sumber independen."},
{q:"Bisakah AI menggantikan guru?",a:"Tidak — dan memahami mengapa itu penting. Laporan UNESCO tentang AI dalam Pendidikan (2023): AI tidak memiliki intuisi pedagogis — tidak bisa mendeteksi bahwa anak bingung, lelah, atau butuh penjelasan yang sangat berbeda. Rumusan terbaik: AI adalah mitra belajar yang berpengetahuan, bukan guru. Pola sehat: berpikir 5 menit sendiri → tanya AI → verifikasi dengan manusia."},
{q:"Bagaimana saya mencegah ketergantungan AI pada anak saya?",a:"Tiga aturan berbasis bukti: (1) Pikir dulu — AI hanya dikonsultasikan setelah 5 menit upaya mandiri yang sungguh-sungguh. (2) Jelaskan padaku — setelah menggunakan AI, anak harus menjelaskan jawaban dengan kata-katanya sendiri; jika tidak bisa, dia menyalin bukan belajar. (3) Satu hari tanpa AI per minggu — diframing positif: 'melatih otakmu sendiri seperti atlet melatih tubuh mereka.' Penelitian Ericsson (1993) mengkonfirmasi bahwa pengambilan yang penuh usaha membangun jalur saraf yang tahan lama."},
{q:"Pekerjaan apa yang akan ada untuk anak saya di era AI?",a:"WEF Future of Jobs Report (2024): 70% pekerjaan akan berubah signifikan dalam 5 tahun. Peran baru: Peninjau Etika AI, Desainer Interaksi Manusia-AI, Pelatih AI. Pekerjaan yang tetap diminati: yang membutuhkan ketangkasan fisik dan penilaian (dokter bedah, pengrajin) atau empati nyata (terapis, guru, perawat). Lebih penting dari jabatan spesifik: meta-keterampilan bekerja bersama AI — tahu kapan mempercayainya, kapan mempertanyakannya, cara memverifikasi outputnya."}
],
proto_by:"Dari penulis yang sama:",proto_desc:"Panduan sistematis untuk mengkalibrasi ulang pola pikir di era AI — 33 protokol berbasis bukti untuk adaptasi sadar.",
cta_self:"Ikuti tes sendiri →",cta_child:"← Siapkan untuk anak"
},

pt:{
intro:"Este site gratuito e sem anúncios desenvolve verdadeira literacia em IA em crianças de 3 a 17 anos — não apenas como usar ferramentas de IA, mas como pensar criticamente sobre elas. Cada facto está ligado a uma fonte verificada. O progresso permanece no dispositivo; nada é recolhido ou transmitido.",
priv_h:"🔒 Zero recolha de dados",
priv:"Sem cookies, sem rastreamento, sem contas. O progresso é armazenado no localStorage do navegador e nunca sai do dispositivo. O número do certificado é um hash SHA-256 gerado localmente a partir de um timestamp. O código-fonte é público sob GPL v3.",
src_h:"📚 Fontes verificadas",
src:"Os factos ligam-se a fontes primárias: preprints arXiv, relatórios UNESCO, MIT Media Lab, Lei da IA da UE, Stanford Internet Observatory. Sem sensacionalismo, sem antropomorfizar a IA.",
discuss_h:"💬 Tópicos de conversa para a sua família",
discuss:["A Alexa pode sentir a sua falta? Como saberia?","Se a IA escreveu uma história — quem é o verdadeiro autor?","O que a IA faz melhor do que as pessoas? E as pessoas?","Se a IA diz que algo é verdade — como verificaria?","Confiaria na IA para tomar uma decisão importante? Porquê?"],
faq_h:"Perguntas frequentes",
faq:[
{q:"A partir de que idade devo explicar a IA ao meu filho?",a:"Crianças de 3 a 4 anos já interagem com IA através de assistentes de voz. A investigação do MIT Media Lab (Resnick, 2017) mostra que crianças de 5 a 6 anos podem compreender conceitos algorítmicos básicos através do jogo. Não espere pela 'idade certa' — comece com observações simples: 'A Siri não entende piadas porque não sente nada.' Princípio-chave: os conceitos devem preceder as ferramentas em 1 a 2 anos. Uma criança que usa IA sem entender o que é desenvolve dependência passiva em vez de literacia ativa."},
{q:"Como explico a IA a uma criança de 4 a 7 anos?",a:"Use a analogia do livro de receitas: 'A IA é como um enorme livro de receitas — conhece um milhão de receitas mas não sabe quando tens fome.' Ou: 'Imagina que viste 10.000 fotos de gatos. Agora reconheces um gato instantaneamente. A IA faz o mesmo com dados.' Evite a palavra 'inteligente' — cria falsa antropomorfização. Diga 'bem treinada' ou 'muito boa em padrões'. Classifiquem juntos objetos por cor, depois explique que é exatamente isso que a IA faz com números."},
{q:"O que as crianças nunca devem partilhar com chatbots de IA?",a:"Trate a IA como um quadro de avisos público — assuma que tudo o que é digitado pode ser lido por estranhos. Especificamente: nome completo + morada em conjunto, palavras-passe, informações de pagamento, detalhes médicos, fotos íntimas. Para crianças pequenas: 'O que não gritarias num centro comercial, não escrevas à IA.' A Lei da IA da UE (2024) classifica os sistemas de IA que interagem com crianças como de alto risco."},
{q:"O que são alucinações de IA — e como explicá-las?",a:"Alucinações de IA são respostas erradas mas confiantes. Um modelo de linguagem pode citar um livro inexistente ou inventar estatísticas com total certeza. Para crianças: 'Imagina um colega que nunca admite não saber — inventa sempre algo. É assim que a IA funciona quando está incerta.' Regra prática para crianças a partir de 8 anos: qualquer facto da IA precisa de ser verificado em pelo menos uma fonte independente."},
{q:"A IA pode substituir um professor?",a:"Não — e perceber porquê é importante. Relatório UNESCO sobre IA na Educação (2023): a IA não tem intuição pedagógica — não pode detetar que uma criança está confusa, cansada ou precisa de uma explicação fundamentalmente diferente. A IA não pode modelar humildade intelectual nem a alegria da descoberta partilhada. Melhor enquadramento: a IA é um parceiro de estudo com conhecimento, não um professor. Padrão saudável: pensar 5 minutos sozinho → perguntar à IA → verificar com um humano."},
{q:"Como previno a dependência de IA no meu filho?",a:"Três regras baseadas em evidências: (1) Pensar primeiro — a IA só é consultada após uma tentativa solo genuína de 5 minutos. (2) Explicar — depois de usar IA, a criança deve explicar a resposta com as suas próprias palavras; se não conseguir, copiou em vez de aprender. (3) Um dia sem IA por semana — formulado positivamente: 'treinar o próprio cérebro como os atletas treinam o corpo.' A investigação de Ericsson (1993) confirma que o esforço de recuperação constrói vias neurais duradouras."},
{q:"Que empregos existirão para o meu filho na era da IA?",a:"WEF Future of Jobs Report (2024): 70% dos empregos mudarão significativamente em 5 anos. Novas funções: Revisor de Ética de IA, Designer de Interação Humano-IA, Treinador de IA. Funções persistentemente procuradas: as que requerem destreza física e julgamento (cirurgiões, artesãos) ou empatia genuína (terapeutas, professores, cuidadores). Mais importante do que títulos específicos: a metacompetência de trabalhar ao lado da IA — saber quando confiar, quando questionar, como verificar."}
],
proto_by:"Do mesmo autor:",proto_desc:"Um guia sistemático para reiniciar a mentalidade na era da IA — 33 protocolos baseados em evidências para adaptação consciente.",
cta_self:"Fazer o teste eu mesmo →",cta_child:"← Configurar para criança"
},

tr:{
intro:"Bu ücretsiz, reklamsız site 3–17 yaş arası çocuklarda gerçek AI okuryazarlığı geliştirir — yalnızca AI araçlarını kullanmayı değil, bunlar hakkında eleştirel düşünmeyi. Her bilgi doğrulanmış bir kaynağa bağlıdır. İlerleme cihazda kalır; hiçbir şey toplanmaz veya iletilmez.",
priv_h:"🔒 Sıfır veri toplama",
priv:"Çerez yok, izleme yok, hesap yok. İlerleme, tarayıcının localStorage'ında saklanır ve asla cihazı terk etmez. Sertifika numarası, zaman damgasından yerel olarak oluşturulan SHA-256 karma değeridir. Kaynak kodu GPL v3 altında kamuya açıktır.",
src_h:"📚 Doğrulanmış kaynaklar",
src:"Bilgiler birincil kaynaklara bağlıdır: arXiv ön baskıları, UNESCO raporları, MIT Media Lab, AB Yapay Zeka Yasası, Stanford İnternet Gözlemevi. Sansasyon yok, AI'ın insanlaştırılması yok.",
discuss_h:"💬 Aileniz için konuşma başlatıcılar",
discuss:["Alexa siz yokken sizi özleyebilir mi? Bunu nasıl bilirdiniz?","AI bir hikaye yazdıysa — gerçek yazar kim?","AI insanlardan neyi daha iyi yapabilir? İnsanlar ne yapar?","AI bir şeyin doğru olduğunu söylerse — bunu nasıl doğrulardınız?","Önemli bir karar için AI'a güvenir miydiniz? Neden?"],
faq_h:"Sık sorulan sorular",
faq:[
{q:"Çocuğuma AI'ı kaç yaşından itibaren açıklamalıyım?",a:"3–4 yaşındaki çocuklar sesli asistanlar aracılığıyla zaten AI ile etkileşime giriyor. MIT Media Lab araştırması (Resnick, 2017): 5–6 yaşındaki çocuklar oyun yoluyla temel algoritmik kavramları kavrayabilir. 'Doğru yaş' beklemeyin — basit gözlemlerle başlayın: 'Siri fıkraları anlamıyor çünkü hiçbir şey hissetmiyor.' Temel ilke: kavramlar araçlardan 1–2 yıl önde olmalı. Ne olduğunu anlamadan AI kullanan çocuk aktif okuryazarlık yerine pasif bağımlılık geliştirir."},
{q:"4–7 yaşındaki çocuğa AI nasıl açıklanır?",a:"Tarif kitabı benzetmesini kullanın: 'AI, devasa bir tarif kitabı gibi — bir milyon tarif biliyor ama ne zaman aç olduğunu bilmiyor.' Ya da: 'On bin kedi fotoğrafı gördüğünü hayal et. Artık anında kedi tanıyorsun. AI de verilerle aynısını yapıyor.' 'Akıllı' kelimesinden kaçının — yanlış insanlaştırma yaratır. 'İyi eğitilmiş' veya 'kalıplar konusunda çok iyi' deyin. Birlikte nesneleri renklerine göre sıralayın, sonra AI'ın sayılarla tam olarak bunu yaptığını açıklayın."},
{q:"Çocuklar AI chatbotlarla asla ne paylaşmamalı?",a:"AI'ı kamuya açık bir ilan tahtası gibi ele alın — yazılanların yabancılar tarafından okunabileceğini varsayın. Özellikle: tam ad + ev adresi birlikte, şifreler, ödeme bilgileri, tıbbi ayrıntılar, mahrem fotoğraflar. Küçük çocuklar için: 'Alışveriş merkezinde bağırarak söylemeyeceğin şeyi AI'a yazma.' AB AI Yasası (2024) çocuklarla etkileşime giren AI sistemlerini yüksek riskli olarak sınıflandırır."},
{q:"AI halüsinasyonları nedir — nasıl açıklanır?",a:"AI halüsinasyonları, güvenli ama yanlış yanıtlardır. Bir dil modeli var olmayan bir kitabı alıntılayabilir veya uydurma istatistikleri tam kesinlikle sunabilir. Çocuklar için: 'Hiçbir zaman bilmediğini kabul etmeyen bir sınıf arkadaşı hayal et — her zaman bir şeyler uydurur. AI emin olmadığında böyle çalışır.' 8+ çocuklar için pratik kural: AI'dan gelen herhangi bir bilgi en az bir bağımsız kaynakta doğrulanmalıdır."},
{q:"AI bir öğretmenin yerini alabilir mi?",a:"Hayır — ve nedenini anlamak önemli. UNESCO AI in Education Raporu (2023): AI'ın pedagojik sezgisi yok — bir çocuğun kafasının karıştığını, yorgun olduğunu veya tamamen farklı bir açıklama gerektirdiğini algılayamaz. En iyi çerçeveleme: AI, bilgili bir çalışma partneri, öğretmen değil. Sağlıklı örüntü: 5 dakika tek başına düşün → AI'a sor → bir insanla doğrula."},
{q:"Çocuğumda AI bağımlılığını nasıl önlerim?",a:"Kanıta dayalı üç kural: (1) Önce düşün — AI yalnızca gerçek bir 5 dakikalık solo denemeden sonra başvurulur. (2) Bana açıkla — AI kullandıktan sonra çocuk cevabı kendi sözleriyle açıklamalı; yapamıyorsa öğrenmek yerine kopyalamış demektir. (3) Haftada bir AI'sız gün — olumlu çerçeveleme: 'kendi beynini antrenman yapıyor, sporcuların bedenlerini antrenman yaptığı gibi.' Ericsson (1993) araştırması: çaba gerektiren geri çağırma kalıcı sinirsel yollar oluşturur."},
{q:"AI çağında çocuğum için hangi meslekler var?",a:"WEF Geleceğin İşleri Raporu (2024): işlerin %70'i 5 yılda önemli ölçüde değişecek. Yeni roller: AI Etik İnceleyicisi, İnsan-AI Etkileşim Tasarımcısı, AI Eğiticisi. Sürekli talep gören: fiziksel beceri ve yargı (cerrahlar, zanaatkarlar) veya gerçek empati (terapistler, öğretmenler, bakıcılar) gerektiren roller. Belirli iş unvanlarından daha önemli: AI ile etkili çalışmanın meta becerisi — ne zaman güveneceğini, ne zaman sorgulamanın, nasıl doğrulayacağını bilmek."}
],
proto_by:"Aynı yazardan:",proto_desc:"AI çağında zihniyet yeniden başlatma için sistematik bir rehber — bilinçli uyum için 33 kanıta dayalı protokol.",
cta_self:"Testi kendim yapayım →",cta_child:"← Çocuk için ayarla"
},

vi:{
intro:"Trang web miễn phí, không quảng cáo này xây dựng hiểu biết AI thực sự cho trẻ em 3–17 tuổi — không chỉ cách sử dụng công cụ AI, mà cách suy nghĩ phản biện về chúng. Mỗi sự kiện được liên kết với nguồn đã xác minh. Tiến trình lưu trên thiết bị; không có gì được thu thập hay truyền đi.",
priv_h:"🔒 Không thu thập dữ liệu",
priv:"Không cookie, không theo dõi, không tài khoản. Tiến trình lưu trong localStorage của trình duyệt và không bao giờ rời thiết bị. Số chứng chỉ là hash SHA-256 tạo cục bộ từ timestamp. Mã nguồn công khai theo GPL v3.",
src_h:"📚 Nguồn đã xác minh",
src:"Dữ kiện liên kết đến nguồn gốc: preprint arXiv, báo cáo UNESCO, MIT Media Lab, Luật AI EU, Stanford Internet Observatory. Không giật gân, không nhân cách hóa AI.",
discuss_h:"💬 Chủ đề trò chuyện cho gia đình",
discuss:["Alexa có thể nhớ bạn khi bạn vắng không? Làm sao bạn biết?","Nếu AI viết câu chuyện — ai là tác giả thật sự?","AI làm gì tốt hơn người? Người làm gì tốt hơn AI?","Nếu AI nói điều gì là thật — bạn sẽ xác minh thế nào?","Bạn có tin tưởng AI ra quyết định quan trọng không? Tại sao?"],
faq_h:"Câu hỏi thường gặp",
faq:[
{q:"Từ độ tuổi nào nên giải thích AI cho con?",a:"Trẻ 3–4 tuổi đã tương tác với AI qua trợ lý giọng nói. Nghiên cứu MIT Media Lab (Resnick, 2017): trẻ 5–6 tuổi có thể hiểu khái niệm thuật toán cơ bản qua trò chơi. Đừng chờ 'độ tuổi phù hợp' — bắt đầu bằng quan sát đơn giản: 'Siri không hiểu trò đùa vì cô ấy không cảm nhận gì.' Nguyên tắc chính: khái niệm phải đi trước công cụ 1–2 năm. Trẻ dùng AI trước khi hiểu nó là gì sẽ phát triển sự phụ thuộc thụ động thay vì hiểu biết chủ động."},
{q:"Làm thế nào giải thích AI cho trẻ 4–7 tuổi?",a:"Dùng ví dụ sách nấu ăn: 'AI giống như cuốn sách nấu ăn khổng lồ — biết hàng triệu công thức nhưng không biết khi nào con đói.' Hoặc: 'Hãy tưởng tượng con xem 10.000 ảnh mèo. Giờ con nhận ra mèo ngay lập tức. AI làm điều tương tự với dữ liệu.' Tránh từ 'thông minh' — nó tạo ra nhân cách hóa sai. Nói 'được đào tạo tốt' hoặc 'rất giỏi nhận dạng mô hình'. Cùng phân loại đồ vật theo màu sắc, rồi giải thích đó chính xác là những gì AI làm với con số."},
{q:"Trẻ không nên chia sẻ gì với chatbot AI?",a:"Coi AI như bảng thông báo công cộng — giả định mọi thứ được gõ vào đều có thể bị người lạ đọc. Cụ thể: họ tên đầy đủ + địa chỉ nhà cùng nhau, mật khẩu, thông tin thanh toán, chi tiết y tế, ảnh riêng tư. Với trẻ nhỏ: 'Điều gì con không hét to ở trung tâm mua sắm, đừng gõ vào AI.' Luật AI EU (2024) phân loại hệ thống AI tương tác với trẻ em là rủi ro cao."},
{q:"Ảo giác AI là gì — và giải thích thế nào?",a:"Ảo giác AI là câu trả lời sai nhưng tự tin. Mô hình ngôn ngữ có thể trích dẫn cuốn sách không tồn tại hoặc trình bày thống kê bịa đặt với sự chắc chắn hoàn toàn. Với trẻ em: 'Hãy tưởng tượng bạn học không bao giờ thừa nhận không biết — luôn bịa đặt điều gì đó. AI hoạt động như vậy khi không chắc chắn.' Quy tắc cho trẻ 8+: bất kỳ thông tin nào từ AI cần được xác minh ít nhất một nguồn độc lập."},
{q:"AI có thể thay thế giáo viên không?",a:"Không — và hiểu tại sao rất quan trọng. Báo cáo UNESCO về AI trong Giáo dục (2023): AI thiếu trực giác sư phạm — không thể phát hiện trẻ đang bối rối, mệt mỏi hay cần cách giải thích hoàn toàn khác. Cách diễn đạt tốt nhất: AI là đối tác học tập có kiến thức, không phải giáo viên. Mô hình lành mạnh: suy nghĩ 5 phút một mình → hỏi AI → xác minh với người."},
{q:"Làm thế nào ngăn con phụ thuộc vào AI?",a:"Ba quy tắc dựa trên bằng chứng: (1) Suy nghĩ trước — AI chỉ được hỏi sau 5 phút thử một mình thực sự. (2) Giải thích cho tôi — sau khi dùng AI, con phải giải thích câu trả lời bằng lời của mình; nếu không thể, con đã sao chép chứ không học. (3) Một ngày không AI mỗi tuần — đóng khung tích cực: 'luyện não như vận động viên luyện thể lực.' Nghiên cứu Ericsson (1993): nỗ lực ghi nhớ và giải quyết xây dựng đường thần kinh bền vững."},
{q:"Thời đại AI sẽ có những công việc gì cho con tôi?",a:"WEF Future of Jobs Report (2024): 70% việc làm sẽ thay đổi đáng kể trong 5 năm. Vai trò mới: Người xem xét Đạo đức AI, Nhà thiết kế Tương tác Người-AI, Huấn luyện viên AI. Công việc luôn được cầu: đòi hỏi sự khéo léo thể chất và phán xét (phẫu thuật viên, thợ thủ công) hoặc sự đồng cảm thực sự (nhà trị liệu, giáo viên, người chăm sóc). Quan trọng hơn tên nghề cụ thể: kỹ năng meta làm việc bên cạnh AI — biết khi nào tin tưởng, khi nào đặt câu hỏi, cách xác minh."}
],
proto_by:"Từ tác giả tương tự:",proto_desc:"Hướng dẫn hệ thống để khởi động lại tư duy trong thời đại AI — 33 giao thức dựa trên bằng chứng để thích nghi có ý thức.",
cta_self:"Tự làm bài kiểm tra →",cta_child:"← Thiết lập cho trẻ"
}
};
